#------------------------------------------------------------------------------------------
#										MAD LIBS
#------------------------------------------------------------------------------------------
first_adjective = input("Write an Adjective: ")
second_noun = input("Write a Noun: ")
third_adjective = input("Write an Adjective: ")
fourth_plural_noun = input("Write an Adverb: ")
fifth_verb_ending = input("Write a Verb Ending in 'ing': ")
sixth_silly_plural_noun = input("Write a Silly Plural Noun: ")
seventh_adjective = input("Write an Adjective: ")
eighth_plural_noun = input("Write a Plural Noun: ")
ninth_first_name = input("Write a First Name: ")
tenth_number = input("Write a Number: ")
eleventh_first_names = input("Write a First Name: ")
twelveth_first_names = input("Write a First Name: ")
thirteenth_first_names = input("Write a First Name: ")
fourteenth_plural_noun = input("Write a Plural Noun: ")


print("When we look up to the sky on a ")
print(first_adjective)
print( "summer's night, we see millions of tiny spots of light. Each one represents a")
print(second_noun)
print("which is the center of a")
print(third_adjective)
print("solar system with dozens of ")
print(fourth_plural_noun)
print("revolving around a distant sun. Sometimes these suns expand and begin ")
print(fifth_verb_ending)
print("their neighbors. Soon they will become so big, they will turn into ")
print(sixth_silly_plural_noun)
print(". Eventually they subside and turn into")
print(seventh_adjective)
print("giants or perhaps black ")
print(eighth_plural_noun)
print(". Our own planet, which we call")
print(ninth_first_name)
print(" circles around our sun ")
print(tenth_number)
print("times every year. There are eight other planets in our solar system. They are named")
print(eleventh_first_names)
print(twelveth_first_names)
print(thirteenth_first_names)
print(", Jupiter and Mars. Scientist who study these planets are called ")
print(fourteenth_plural_noun)

